### ISSUE TITLE
Choose an open source license

### ISSUE THREAD

**Issue by cavebeat** [RudraNirvan/hack.chat-android#8]
Hi @RudraNirvan 

Please have a look at https://choosealicense.com/ and pick one. 

This makes it easier for the community to fork and contribute to your code and improve it togehter and make it even better. 

I suggest to use GPLv3 - https://www.gnu.org/licenses/quick-guide-gplv3.html

thx in advance

**Comment by RudraNirvan** [comment]
@cavebeat thanks for the suggestion. Have added the MIT license.
